version: '3.8'
services:
  mongodb:
    # image: mongo:${MONGODB_VERSION}
    # image: mongo:7.3.3
    image: mongo:latest
    ports:
      - 27025:27017
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--bind_ip_all"]

volumes:
  mongodb_data: